---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 127.0.0.1
  disableDefaultCNI: true
  podSubnet: "10.2.0.0/16"
  serviceSubnet: "100.2.0.0/16"
  kubeProxyMode: "none"
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 32080
        protocol: TCP
        listenAddress: "0.0.0.0"
      - containerPort: 443
        hostPort: 32443
        protocol: TCP
        listenAddress: "0.0.0.0"
