---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
      - addresses:
          - 172.1.255.10-172.1.255.250
        name: default
        protocol: layer2
